# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact Form
  description: Contact form section
  icon: send_to_mobile
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  form_heading: ""
  name_placeholder: "Your Name"
  email_placeholder: "Email Address"
  message_placeholder: "Your Message"
  submit_button_text: "Send Message"
  address: ""
  email: ""
  phone: ""
  facebook: ""
  twitter: ""
  linkedin: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheading: We are Professionals
  heading: Don’t Hesitate to contact with us for any kind of information
  form_heading: Contact Form
  name_placeholder: "Your Name"
  email_placeholder: "Email Address"
  message_placeholder: "Your Message"
  submit_button_text: "Send Message"
  address: Address
  email: contact@mail.com
  phone: +84 9 5555 5555
  facebook: gvnn.vn
  twitter: gvnn.vn
  linkedin: gvnn.vn

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
